name: build
on:
    push:
        tags:
            - '[0-9]+.[0-9]+.[0-9]+'

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [14.x]

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  always-auth: true
                  node-version: ${{ matrix.node-version }}
                  registry-url: https://registry.npmjs.org
                  scope: '@yzfe'
              env:
                  NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
                  NPM_TOKEN: ${{secrets.NPM_YZ_TOKEN}}
                  CI_FE_TOKEN: ${{secrets.CI_FE_TOKEN}}
            - run: npm config set always-auth true
            - run: npm config set @yzfe-private:registry https://npm.yzops.net
            - run: npm config set //npm.yzops.net/:_authToken ${NPM_TOKEN}
            - run: yarn
            - run: yarn build
            - run: npm --no-git-tag-version version ${GITHUB_REF#refs/tags/}
            - run: npm publish
            - run: CI_TOKEN=${CI_FE_TOKEN} yarn docs:build
